spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.opasjdlkcvqnieqskigj&password=RWeU5lm2McNE9vxS
    username: postgres.opasjdlkcvqnieqskigj
    password: RWeU5lm2McNE9vxS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
